[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
authors = [{name = "Pierpaolo Iurato"}]
dependencies = [
  "pandas==2.3.3",
]
description = "Shared utilities for wine quality classification project"
name = "utils"
requires-python = ">=3.7"
version = "0.1.0"
